# ==================
# USING DEPENCANCIES
# ==================
# OUTPUT: DEPENDANCY
# 	command to produce output with dependancy

tester2.txt: tester.txt
	cat tester.txt > tester2.txt

tester.txt:
	echo "this is a test" > tester.txt
